version: '3'
services:
  ad-brasil-site:
    container_name: adbrasil_site_container
    build:
      context: .
      dockerfile: Dockerfile.dev  # Referência ao Dockerfile.dev
    volumes:
      - .:/app  # Monta o diretório atual no container
    ports:
      - "5173:5173"  # Mapeia a porta 5173 do container para a porta 5173 da máquina host -setei essa porta por causa da regra do firewall do meu windows
    environment:
      - CHOKIDAR_USEPOLLING=true  # Habilita o polling para detecção de mudanças em arquivos
